revision/persons/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view

urlpatterns = [
    path('', views.home, name='home'),
    #path('profile/', views.person_create_view, name='person_add'),
    path('<int:pk>/', views.person_update_view, name='person_change'),
    path('register/', views.register, name='register'),
    path('profile/', views.profile, name='profile'),
    path('login/', auth_view.LoginView.as_view(template_name='persons/login.html'), name="login"),
    path('logout/', auth_view.LogoutView.as_view(template_name='persons/logout.html'), name="logout"),


    path('ajax/load-cities/', views.load_cities, name='ajax_load_cities'), # AJAX
]

revision/revision/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('persons.urls'))
]

revision/persons/models.py
from django.db import models


class District(models.Model):
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Branch(models.Model):
    district = models.ForeignKey(District, on_delete=models.CASCADE)
    name = models.CharField(max_length=40)

    def __str__(self):
        return self.name


class Person(models.Model):
    Name = models.CharField(max_length=250)
    DOB = models.DateTimeField()
    Age = models.IntegerField()
    Phone_number = models.IntegerField()
    email = models.EmailField()
    Gender = models.CharField(max_length=250)
    district = models.ForeignKey(District, on_delete=models.SET_NULL, blank=True, null=True)
    branch = models.ForeignKey(Branch, on_delete=models.SET_NULL, blank=True, null=True)
    Documents = models.CharField(max_length=250)
    Account_type = models.CharField(max_length=250)
    def __str__(self):
        return self.name

revision/revisionapp/models.py
from django.db import models

# Create your models here.

revision/users/models.py
from django.db import models

# Create your models here.

revision/persons/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

from persons.models import Person, District,Branch


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

ACCOUNT_CHOICES=[('Savings','savings'),
         ('Current','Current')]
GENDER_CHOICES=[('Male','Male'),
         ('Female','Femal')]
DOCUMENT_CHOICES=[('Aadhar','Aadhar'),
         ('PAN','PAN'),('Passport','Passport'),('DL','DL')]

class PersonCreationForm(forms.ModelForm):
    Account_type = forms.ChoiceField(choices=ACCOUNT_CHOICES, widget=forms.RadioSelect())
    Documents = forms.ChoiceField(choices=DOCUMENT_CHOICES, widget=forms.CheckboxSelectMultiple())
    Gender = forms.ChoiceField(choices=GENDER_CHOICES, widget=forms.RadioSelect())

    class Meta:
        model = Person
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['branch'].queryset = Branch.objects.none()

        if 'country' in self.data:
            try:
                district_id = int(self.data.get('district'))
                self.fields['branch'].queryset = Branch.objects.filter(district_id=district_id).order_by('name')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['branch'].queryset = self.instance.district.branch_set.order_by('name')

revision/persons/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404

from .forms import PersonCreationForm
from .models import Person, Branch,District

from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegisterForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required


def person_create_view(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('person_add')
    return render(request, 'persons/apply.html', {'form': form})


def person_update_view(request, pk):
    person = get_object_or_404(Person, pk=pk)
    form = PersonCreationForm(instance=person)
    if request.method == 'POST':
        form = PersonCreationForm(request.POST, instance=person)
        if form.is_valid():
            form.save()
            return redirect('person_change', pk=pk)
    return render(request, 'persons/apply.html', {'form': form})


# AJAX
def load_cities(request):
    district_id = request.GET.get('district_id')
    branches = Branch.objects.filter(district_id=district_id)
    return render(request, 'persons/city_dropdown_list_options.html', {'branches': branches})
    # return JsonResponse(list(cities.values('id', 'name')), safe=False)


def home(request):
    return render(request, 'home.html')


def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hi {username}, your account was created successfully')
            return redirect('home')
    else:
        form = UserRegisterForm()

    return render(request, 'persons/register.html', {'form': form})


@login_required()
def profile(request):
    form = PersonCreationForm()
    if request.method == 'POST':
        form = PersonCreationForm(request.POST)
        if form.is_valid():
            form.save()
        messages.success(request, f' your application was submitted successfully')
        return redirect('home')

    return render(request, 'persons/apply.html', {'form': form})

revision/revisionapp/views.py
from django.shortcuts import render

# Create your views here.

revision/users/views.py
from django.shortcuts import render

# Create your views here.

revision/persons/templates/home.html
{% extends 'persons/base.html' %}
{% load static %}
{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container">
            <div class="row g-0">
                <div class="col-sm-6 col-md-8" id="header-text">
                  <h1 id="header-h1">Multi-regulated <br> global broker. </h1>
                  <p id="header-paragraph">A trusted destination for traders worldwide, <br> Authorised by FCA, ASIC & FSCA</p>
                  <a class="btn" style="color: white; background-color: #fd5e14;"type="submit" id="body-link-row">Discover More</a>
                </div>

                <div class="col-6 col-md-4" id="header-image"><img src="images/in-liquid-slide-2.svg " alt=""></div>
              </div>
    </div>
{% endblock content %}

revision/persons/templates/persons/apply.html
{% extends 'persons/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}



<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
</head>
<body>
<h2>Person Form</h2>

<form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_district").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const districtID = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'district_id': districtID       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_branch").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>

</body>
{% endblock %}

revision/persons/templates/persons/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'users/css/main.css' %}" type="text/css">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">

  </head>
  <body id="bg" style="background-image: url({% static 'users/images/bg.png' %});">
  {% load static %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark" id="main-navbar">
        <div class="container">
          <a class="navbar-brand" href="{% url 'home' %}"><img src="{% static 'images/in-logo-1.svg' %}" alt="" ></a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <div class="navbar-nav">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
              <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown">Branches</a>
        <div class="dropdown-menu">
            <a href="https://en.wikipedia.org/wiki/Thiruvananthapuram" class="dropdown-item">Trivandrum</a>
            <a href="https://en.wikipedia.org/wiki/Ernakulam" class="dropdown-item">Kochin</a>
            <a href="https://en.wikipedia.org/wiki/Thrissur" class="dropdown-item">Trichur</a>
            <a href="https://en.wikipedia.org/wiki/Kollam" class="dropdown-item">Kollam</a>
            <a href="https://en.wikipedia.org/wiki/Kozhikode" class="dropdown-item">Calicut</a>
            <div class="dropdown-divider"></div>
            <a href="#" class="dropdown-item">Trash</a>
        </div>
    </li>

            </div>
            <form class="d-flex" id="authstyle">
              {% if user.is_authenticated %}
                <a href="{% url 'profile' %}" class="btn" style="color: white; background-color: #fd5e14;"type="submit" id="header-links"> Apply </a>
                <a href="{% url 'logout' %}" class="btn" style="color: white; background-color: #fd5e14;"type="submit" id="header-links"> Logout </a>
              {% else %}
                <a href="{% url 'register' %}" class="btn" style="color: white; background-color: #fd5e14;"type="submit" id="header-links"> Create Account </a>
                <a href="{% url 'login' %}" class="btn" style="color: white; background-color: #fd5e14; margin-left: 10px; "type="submit" id="header-links">Log In</a>
              {% endif %}
              </form>
          </div>
        </div>
    </nav>

      <div>
        <div class="container">
          {% if messages %}
          {% for message in messages %}
            <div class="alert alert-{{message.tags}}">{{message}}</div>
          {% endfor %}
        {% endif %}
        </div>
        {% block content %}
        {% endblock content %}
      </div>

      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
      -->
  </body>
</html>

revision/persons/templates/persons/city_dropdown_list_options.html
<option value="">---------</option>
{% for branch in branches %}
<option value="{{ branch.pk }}">{{ branch.name }}</option>
{% endfor %}

revision/persons/templates/persons/login.html
{% extends 'persons/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4" style="color: white;">Sign In Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="btn ">Sign In</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Don't have an account yet? <a href="{% url 'register' %}">Sign Up Today</a></small>
      </div>
    </form>
    </div>
{% endblock %}</title>

revision/persons/templates/persons/logout.html
{% extends 'persons/base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="container">
        <h1>You have been Logged out</h1>
        <h5><a href="{% url 'login' %}">Login In Again</a></h5>
    </div>
{% endblock %}</title>

revision/persons/templates/persons/profile.html
{% extends 'persons/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}


<h6>Person Form</h6>

<form method="post" id="personForm" data-cities-url="{% url 'ajax_load_cities' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_country").change(function () {
        const url = $("#personForm").attr("data-cities-url");  // get the url of the `load_cities` view
        const countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'country_id': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_city").html(data);  // replace the contents of the city input with the data that came from the server
                /*

                let html_data = '<option value="">---------</option>';
                data.forEach(function (city) {
                    html_data += `<option value="${city.id}">${city.name}</option>`
                });
                console.log(html_data);
                $("#id_city").html(html_data);

                */
            }
        });

    });
</script>


{% endblock %}

revision/persons/templates/persons/register.html
{% extends 'persons/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
          <legend class="border-bottom mb-4" style="color: white;">Join Now</legend>
          {{ form|crispy }}
      </fieldset>
      <div class="form-group" id="signup-button">
          <button class="btn ">Sign Up</button>
      </div>
      <div class="form-group">
          <small class="text-muted ml-3" >Already have an account? <a href="{% url 'login' %}">Sign In</a></small>
      </div>
    </form>
    </div>
{% endblock %}